// يولّد config.js من environment variables.
// يُستدعى قبل vite build على Cloudflare و GitHub Actions و محلياً.
//
// يقرأ من process.env:
//   SUPABASE_URL
//   SUPABASE_KEY        (anon key)
//   VAPID_PUBLIC_KEY
//
// محلياً: لو المتغيّرات غير مضبوطة، يولّد ملفاً بقيم فارغة (الموقع يفتح
// لكن Supabase لن يتصل — كافٍ لاختبار البناء أو CSS).

import { writeFileSync, readFileSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');
const target = resolve(root, 'config.js');

const env = {
  SUPABASE_URL: process.env.SUPABASE_URL || '',
  SUPABASE_KEY: process.env.SUPABASE_KEY || '',
  VAPID_PUBLIC_KEY: process.env.VAPID_PUBLIC_KEY || ''
};

// السكربت يطبع توقيعاً في أول سطر يميّز الملفات المُوَلَّدة.
// لو الملف موجود ومكتوب يدوياً (لا يبدأ بالتوقيع)، نحترمه ولا نلمسه.
const SIGNATURE = '// AUTO-GENERATED by scripts/generate-config.js — لا تعدّله يدوياً';

if (existsSync(target)) {
  const head = readFileSync(target, 'utf8').slice(0, SIGNATURE.length);
  if (head !== SIGNATURE) {
    console.log('[generate-config] config.js موجود ومكتوب يدوياً — لا نستبدله');
    process.exit(0);
  }
}

const missing = Object.entries(env).filter(([, v]) => !v).map(([k]) => k);
if (missing.length) {
  // في CI: missing env vars خطأ صريح
  if (process.env.CI || process.env.GITHUB_ACTIONS || process.env.CF_PAGES) {
    console.error(`[generate-config] متغيّرات بيئة مفقودة في CI: ${missing.join(', ')}`);
    process.exit(1);
  }
  // محلياً: تحذير، نتابع بقيم فارغة
  console.warn(`[generate-config] محلياً، المتغيّرات الناقصة: ${missing.join(', ')} (سيُولَّد config بقيم فارغة)`);
}

const content = `${SIGNATURE}
window.APP_CONFIG = {
  SUPABASE_URL: ${JSON.stringify(env.SUPABASE_URL)},
  SUPABASE_KEY: ${JSON.stringify(env.SUPABASE_KEY)},
  VAPID_PUBLIC_KEY: ${JSON.stringify(env.VAPID_PUBLIC_KEY)}
};
`;

writeFileSync(target, content, 'utf8');
console.log(`[generate-config] تم توليد config.js (${content.length} بايت)`);
